### ISSUE TITLE
Will the code be released ?

### ISSUE THREAD

**Issue by tranxuantuyen** [heshuting555/DsHmp#1]
Hi, congratulations for your great work! Do you have plans to release the code? Thanks

**Comment by heshuting555** [comment]
Thank you for your interest!

Our code will be open source at the end of May!

**Comment by Tavarich** [comment]
Thanks for your great work! You mentioned the code would be open source by the end of May. Since it's now June 7th, I am wondering when the code will be released actually. Thank you!
