### ISSUE TITLE
How to evaluate on Ref-Youtube-VOS and Ref-DAVIS?

### ISSUE THREAD

**Issue by wooj0216** [heshuting555/DsHmp#14]
Hello, thank you for your great work!

I would like to ask you if there is a way to test your model in Ref-Youtube-VOS and Ref-DAVIS dataset.

I found that the evaluation server for both dataset is closed, so I'm curious how to reproduce the results written on your paper.

Thank you very much.

**Comment by boqchen** [comment]
Hi @wooj0216. 

I saw you closed the issue. I was wondering if you found the evaluation. From my side I also saw it was closed.

Thanks!

**Comment by Sjunshu** [comment]
> 您好。
> 
> 我看到你关闭了这个问题。我想知道你有没有找到评估。从我这边我也看到它已经关闭了。
> 
> 谢谢！

Hello, have you solved this problem?

**Comment by wooj0216** [comment]
Sorry for the late reply! @Sjunshu @boqchen 
I found that the evaluation set of Ref-DAVIS is available, so I was able to solve the issue with it.
Also, I discovered that the Ref-Youtube-VOS evaluation server is open [here](https://codalab.lisn.upsaclay.fr/competitions/13520).

I hope this helps resolve your problem.
