### ISSUE TITLE
Simple question regarding model training

### ISSUE THREAD

**Issue by golddohyun** [heshuting555/DsHmp#7]
Hello, thank you for the excellent work!

I have some questions about model training.
I downloaded the backbone weights of MaskFormer2 (model_final_86143f.pkl), and I want clarification on where in the code these weights are being used.

Is it correct to specify the path to the backbone weight .pkl file in the MODEL.WEIGHTS [path_to_weights] section of the training script?

Thanks:)

**Comment by heshuting555** [comment]
The code is based on the detectron framework. You can learn about this framework. It will load backbone weight by default.

**Comment by golddohyun** [comment]
Thanks for the reply! So you mean that i don't have to directly write
MODEL.WEIGHTS ./model_final_86143f.pkl
in the training script?

**Comment by heshuting555** [comment]
You need or you can put it in the config.yaml

**Comment by golddohyun** [comment]
ahh great all issues solved. thanks!
